### ISSUE TITLE
Kinship analysis

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#22]
lcMLkin, pmr, READ

**Comment by apeltzer** [comment]
https://bitbucket.org/tguenther/read

**Comment by TCLamnidis** [comment]
I have made a little script for calculating pMMR (from EIGENSTRAT genotypes only currently):
https://github.com/TCLamnidis/pMMRCalculator

This is already on bioconda, so it should be possible to integrate into eager.

**Comment by apeltzer** [comment]
You were just assigned to add this 😆 Thank you 🙇‍♂️

**Comment by jfy133** [comment]
After talking with @TCLamnidis, we decided kinship analysis is probably out of the scope of EAGER because of the EIGENSTRAT stuff. He is making a different pipeline which actually runs from BAMs and does the EIGENSTRAT trickery, so it makes more sense there.

Also you have to pull together lots of individuals and actually are running _analysis_ on them, rather than just processing files into output for downstream analysis. Which I think this isn't what EAGER should be doing - the most it should would be reporting standard information from 'screening' so to say.

Therefore going to close this!
