### ISSUE TITLE
Get Software Versions process not run if DamageProfiler skipped

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#237]
**Describe the bug**
If you do not have damageprofiler running in your run (with `--skip_deduplication`), `get_software_versions` process is not executed.

**To Reproduce**
See above

**Expected behaviour**
`get_software_versions` always run with whatever tools are accessible.

**Additional context**
Partly due to the awkward way of getting the DamageProfiler versions (i.e. from the log file), so must be given to the process as an input channel.

**Comment by jfy133** [comment]
This is also an issue for the GATK_UG branch

**Comment by jfy133** [comment]
Possible solution?

https://github.com/nextflow-io/patterns/blob/master/docs/optional-input.adoc

**Comment by apeltzer** [comment]
Yeah, the problem is that the DamageProfiler tool doesn't write out a JSON file unfortunately with the information that we'd need at the moment. Since v0.4.6 it can do that, but MultiQC v1.8 isn't out (yet) that could parse this information automatically from the JSON that DamageProfiler nowadays creates automatically. 

=> Once we have MultiQC v1.8, this will be gone immediately and we can also the same approach than with other tools ...

**Comment by jfy133** [comment]
Coming this afternoon from @aidaanva

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/eager/pull/292
