### ISSUE TITLE
Error executing process > 'damageprofiler 

### ISSUE THREAD

**Issue by zhongxing123** [nf-core/eager#543]
hi，
I am a novice with eager2. I still can't use it proficiently. when I start running my own ancient DNA analysis, I got the following error： 
The full error message was:

Error executing process > 'damageprofiler (test_R1.mapped_rmdup)'

Caused by:
  Missing output file(s) `test_R1.mapped_rmdup/*.txt` expected by process `damageprofiler (test_R1.mapped_rmdup)`

Command executed:

  damageprofiler -i test_R1.mapped_rmdup.bam -r Sus_scrofa_mitochondrion.fasta -l 100 -t 15 -o . -yaxis_damageplot 0.30

Command exit status:
  0

Command output:
  DamageProfiler v0.4.9
Could you give me some suggestions about this error
thanks
zhongxing

**Comment by jfy133** [comment]
Hi @zhongxing123 

Hm, that's worrying and sorry about that. 

It looks like DamageProfiler works OK as it's just prints the version with no error. If you go into the work directory (printed to screen below the error), you should see the log files for DamageProfiler, and that might tell you what happened. I've seen this behaviour before when not enough reads mapped to generate damageProfiles (this has been fixed in a newer version of DamageProfiler I believe).

That said, what version of eager2 are you using? If you're running v2.1, it's unfortunately a little buggy and I would instead recommend trying the current dev version `-r dev`, but note that the structure has been changed (to address some of those bugs) so the command might not directly work - check before running.

But if you're already on `dev`, could you please send: the command you used, and the  `.nextflow.log` file.

Cheers,

**Comment by jfy133** [comment]
Closing this now as there has been no more information for over a month. Please feel free to open again if `-r dev` doesn't work.
