### ISSUE TITLE
dedup heap memory seemingly not set properly

### ISSUE THREAD

**Issue by amakunin** [nf-core/eager#561]
Hi, 

First of all, thank you the developers for providing such a comprehensive workflow for ancient DNA analysis!

I've been running nextflow 2.1.0 with singularity for deps management and with a config added to work on a LSF bsub system. 

In processing my data I recurrently encountered `java.lang.OutOfMemoryError` error in several samples. I've tried increasing the memory allocation by changing dedup process label from `mc_small` to `mc_medium`, but with no luck. I then checked the memory consumption from LSF logs and saw that the failed jobs used a little bit over 1GB RAM. 

I then explicitly modified dedup memory consumption within .command.sh script:
`dedup -Xmx48g -i DA010.1.fastq.combined.fq.mapped.bam -m -o . -u`
where 48GB requirement matched the LSF memory limit set by .command.run script, re-submitted the job, and it successfully completed with 6329 MB RAM peak usage.

Could this be an issue within eager or dedup code? Or is this more likely due to [nextflow LSF configuration](https://www.nextflow.io/docs/latest/executor.html#lsf)? Anyways, other steps did not have any problems with memory setting.

**Comment by jfy133** [comment]
Hi Alex,

This is a known problem in that version of eager (I assume you mean nf-core/eager 2.1.0, rather than nextflow 2.1.0, as the latter doesn't exist ;) ).

We had thought at that time for 2.1.0 that the java allocation would work natively but we later found out it didn't

In the current development version (specified with nextflow `-r dev`) , we fixed this by specifying directly to dedup the amount of maximum memory it can use. You can see this here:

https://github.com/nf-core/eager/blob/cf7d0574e6047b1da3686d5fcb76dd90f6129dac/main.nf#L1999

I would therefore recommend using that version of nf-core/eager instead. It should be released as stable hopefully in about a month, but you can still use it already - just note down the commit hash when you run `nextflow pull nf-core/eager -r dev` to download that version, as this you could report in SIs/papermethods.  

Please note however there are quite a few changes in that version, so please check the documentation before re-running - for example the default dedupper is now Picard's MarkDuplicates as DeDup unfortunately has some issues which means it can only be properly used in certain cases (basically, you need pairedEnd data where the vast majority of reads actually merge, as singletons or lone F- or R- reads will not be dedupped properly).

Cheers,

**Comment by jfy133** [comment]
I will close this for now, but feel free to re-open a new issue if you come across more infos. You're also more than welcome to join the nf-core slack channel and ask questions in the channel #eager  (see READMe for the link)

**Comment by amakunin** [comment]
Hi, thanks for quick response - yes, that looks like the fix I was anticipating! Great hint on the defaults change - in our case, we are only using merged reads due to small fragment lengths, so will probably go ahead with that for now.

PS indeed, i meant eager 2.1.0 :)

**Comment by jfy133** [comment]
Btw, if it doesn't already exists, you could potentially set up a nf-core institutional profile at https://github.com/nf-core/configs

You can also set up pipeline specific ones (e.g. if you're group/institute often deals with deep sequencing data, and you want to bump the defaults without having to make personal profiles/editing the code etc.).

Happy to guide if you need!
