### ISSUE TITLE
markduplicates  error Process requirement exceed available CPUs -- req: 2; avail: 1

### ISSUE THREAD

**Issue by marcovth** [nf-core/eager#619]
I got this error, even though --max_cpus 48 was set ...

salloc --time=12:0:0 --ntasks=48 --mem-per-cpu=3G
module load nextflow
module load singularity

nextflow run nf-core/eager --input './VK446chrYx37.bam' --single_end --bam \
	--fasta './Hg19ChrY.fa' --saveReference --outdir './VK446Hg19ChrY' --max_cpus 48 -profile singularity

```
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'markduplicates (VK446chrYx37)'

Caused by:
  Process requirement exceed available CPUs -- req: 2; avail: 1

Command executed:

  ## To make sure direct BAMs have a clean name
  if [[ "VK446chrYx37.bam" != "VK446chrYx37.bam" ]]; then
    mv VK446chrYx37.bam VK446chrYx37.bam
  fi

  picard -Xmx4096M -Xms4096M MarkDuplicates INPUT=VK446chrYx37.bam OUTPUT=VK446chrYx37_rmdup.bam REMOVE_DUPLICATES=TRUE AS=TRUE METRICS_FILE="VK446chrYx37_rmdup.metrics" VALIDATION_STRINGENCY=SILENT
  samtools index VK446chrYx37_rmdup.bam

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /project/xxx/xxx/xxx/work/97/e2250630f0a8b1f5eb80f0d9e5205b

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named .command.sh

```

**Comment by jfy133** [comment]
Hi @marcovth 

I assume you're working on a cluster? The issue here is that it looks like you have not set up a cluster profile, so Nextflow doesn't know how to correctly submit jobs.

For example, in eager we've set up that markduplicates always requires more than one core (as it is a multi-threaded program), however that particular job has somehow been sent to a node with only a single CPU.

```
  Process requirement exceed available CPUs -- req: 2; avail: 1
```

`--max_cpus` only specifies that Nextflow can only generate jobs requesting a maximum of this value, i.e. the particular flag does not tell Nextflow to request 48 CPU nodes.

I would recommend looking at nf-core/configs (https://nf-co.re/usage/configuration#shared-nf-coreconfigs) to look into setting up a proper institutional/cluster profile that correctly submits jobs for you.

Let us know if you have any more questions.

**Comment by marcovth** [comment]
Unfortunately, I think the config thing will kill it for me. It looks too complicated.

Is there an option for nextflow to simply print out the pipeline commands so that I can run and test those myself, step by step?

**Comment by jfy133** [comment]
Hi @marcovth,

No, there is not this functionality in Nextflow unfortunately. Also this wouldn't really solve your problem (or would at least defeat the point of running nf-core/eager). From the error it just looks like your job was just sent to an incompatible node, so the pipeline does look it's mostly working for you already. 

But given that you're running on a cluster, and this is exactly what Nextflow is optimised for (if set up correctly), I would still strongly recommend you trying to write a config. we are happy to run through setting up a config for you if you join the [nf-core slack](https://nf-co.re/join/slack) and join the #eager or #configs channel! It looks like the cluster you are on is running on slurm which is what our cluster uses (https://github.com/nf-core/configs/blob/master/conf/shh.config or https://github.com/nf-core/configs/blob/master/conf/mpcdf.config), so it should be quite straightforward to adapt! We would just need some basic information about the HPC - if there is any public documentaiton for your particular cluster you can send that already and I could draft one for you to try already, otherwise we can just talk on slack and Ican ask you for the relevent info.

**Comment by apeltzer** [comment]
Exactly as James above said - happy to help here. Its not as complicated as you might think it it ;-) And then its fairly easy to run any nf-core pipeline in the end :-)
