### ISSUE TITLE
Paper: using bwa mem instead of bwa aln to speedup the pipeline

### ISSUE THREAD

**Issue by teepean** [nf-core/eager#643]
I came across a paper called "An efficient pipeline for ancient DNA mapping and recovery of endogenous ancient DNA from whole‐genome sequencing data" and from there a quote: 

> We found that BWA mem with the parameters ‐k = 19 and ‐r = 2.5 was comparable to BWA aln with MS parameters ( Schubert et al., 2012) when considering the recovery of ancient DNA, but had a significantly shorter running time than did BWA aln with MS parameters.

The other conclusion the paper has:

> For the recovery of endogenous DNA from ancient sequencing data with homologous contaminations, we recommend screening of reads with parameters: –DeamNum = 1, –DetectRange = 15, and –DoubleOrSingle = or, which could remove more than 99% of homologous DNA contaminations from the raw contaminated sequencing data. Overall, these recommendations for ancient DNA mapping and separation of endogenous DNA can benefit ancient DNA studies, especially for samples preserved under poor conditions.

Worth including in eager?

https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.7056

**Comment by apeltzer** [comment]
BWA mem is already available in the pipeline (and was available in EAGERv1 the predecessor since 2013...), one could simply use the parameters that were evaluated in the paper you posted if one wants to. There is also another paper by _Poulet et al_ (see https://www.frontiersin.org/articles/10.3389/fevo.2020.00105/full) who evaluated Bowtie2 and BWA mem which is why we added that particularly to the pipeline too 😄 They don't agree on the BWA mem improvement, rather make the recommendation of Bowtie2.

What I dislike about the paper you posted there: Zero acknowledgment that there were published papers that provided evidence for the BWA mem situation (e.g. Arora 2014 on Syphilis, which was the main reason to have this in EAGERv1 already - this paper is six years published by now!). Certainly not your fault, but it seems that some people simply overlook that there was prior work on this. That paper doesn't even bother to cite Paleomix and EAGERv1, both of which are real and implemented pipelines whereas the authors simply share a single (!) tool of the "pipeline" they built. I'm not in general criticizing the effort or what has been done in that particular paper, but it has not been done with scientific transparency and full scrutiny to be fair. 

If I intend to work on a bioinformatics analysis pipeline in the particular subfield of ancient DNA, there is a bunch of existing prior work (Kircher 2012, Schubert 2012/2014, Peltzer 2016, Link 2017, Fellows Yates 2020) that one should at least cite. If I evaluate alignment methods, I should probably cite the above mentioned Poulet 2020 paper, too - and probably a bunch of others as well.

Sorry for the rant, again - not your fault.

**Comment by jfy133** [comment]
Hi @teepean, thanks for sending the paper.

As @apeltzer says above, `bwa mem` is already included in eager. However given `aln` is still more popular in aDNA analysis (as it was specifically designed for very short reads, whereas mem is designed for reads ~100bp), we would rather keep it the default for the time being - at least until the field changes.

 For the AncFil thing it looks like it does the same as PMDtools, just faster. This is indeed principle interesting, but again we would rather wait until we see whether the field adopts this as an alternative.

I will close this for now as there is nothing 'new' necessarily from this paper. However we can re-open it in the future if other people request the functionality.
