### ISSUE TITLE
AWS S3 Results are incomplete

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#675]
The results that we currently have in AWS S3 as results (even on the tiny testdata, not necessarily full test data!) are not complete. Can only find a batch of results unfortunately there... 

![image](https://user-images.githubusercontent.com/2359510/106738978-e6a8c300-6618-11eb-985c-4884347e1be6.png)

**Comment by jfy133** [comment]
Yeah, I think I already fixed that

![image](https://user-images.githubusercontent.com/17950287/106744893-a3eae900-6620-11eb-8b07-5eac7dd77d66.png)

631.. basically the nextflow patch release was pulled rather than 20.04, but the patch release had a bug where it didn't accept nested parameters... so I've bumped the minimum release to 20.07.

**Comment by jfy133** [comment]
Actually, will keep this open until the next release to make sure it worked porperly!

**Comment by apeltzer** [comment]
Sounds good to me 👍🏻 Thanks for looking into it!

**Comment by jfy133** [comment]
For proper link PR with the fix: https://github.com/nf-core/eager/pull/663
