### ISSUE TITLE
workflow staging and caching issues

### ISSUE THREAD

**Issue by yassineS** [nf-core/eager#798]
I am running Eager v2.3.5 and nextflow 21.04.2.

I observed a few bugs which I am summarising here:
- the following steps don't cache even if all jobs finish successfully: library_merge, damageprofiler, bam_trim, mtnucratio, nuclear_contamination, and print_nuclear_contamination
- genotyping_ug doesn't run until all bam_trim jobs are all done, this is odd as genotyping_ug can run on individuals outputs

Are these by design?

**Comment by jfy133** [comment]
Hi @yassineS

This behaviour is an unfortunate side effect of the design.

Essentially what is happening in front of most of those processes is that all files going into those processes are being evaluated whether they should be merged or not (other groups requested the ability to do complex merging strategies, e.g. merging lab damaged-removed libraries with on silico damage removed libraries, like the bam trimming).

For reasons I do not fully understand, nextflow will not execute jobs of stuff that don't need to be merged, until it can evaluate all the files at once (resulting in a chokepoint, essentially), which is why downstream processes won't be executed until every file is through the chokepoint.

This also relates to point 1, as I believe there something (also something I've noticed but can't work out) where nextflow isn't sure whether these merged files have changed or not, so the cached files aren't used.

Overall: I'm aware of the behaviour, seen it myself, but not looked closely, as nothing is broken with the pipeline per se, even if is not as optimally efficient.

However I will have a closer look today to see if I can see anything.

Also resolving these issues should be easier with the nextflow DSL2 rewrite which we should be starting at the October nf-core Hackathon.

**Comment by jfy133** [comment]
Sorry for the long essay, written from my phone while on the train.

Let me know if it's unclear 😅

**Comment by jfy133** [comment]
Sorry for the long essay, written from my phone while on the train.

Let me know if it's unclear 😅

**Comment by yassineS** [comment]
Many thanks James, this clarifies things to me. For a moment I can Ben wondered if it’s something wrong with my setup. But glad to know that it isn’t.

As you said it’s nice not to have to deal with it, but it doesn’t mean that the pipeline doesn’t work as intended. Happy to close the issue or leave it open.

Cheers,
—Yassine

**Comment by jfy133** [comment]
Lets close for now, and revisit it if the DSL2 refactoring doesn't improve things.
