### ISSUE TITLE
Failed to run the pipline. Got permission denied

### ISSUE THREAD

**Issue by silvewheat** [nf-core/eager#820]
Hi,
   When I run:
nextflow run nf-core/eager --input '*.fastq.gz' --single_end --fasta 'ARS1.fa' -profile docker

The error ocuurred:
![image](https://user-images.githubusercontent.com/19344997/147026242-97ca3b82-dc12-48bd-8f42-447676a746e7.png)
## Log files

[nextflow.log](https://github.com/nf-core/eager/files/7759574/nextflow.log)

## System

- Hardware: single server
- Executor: local
- OS: Ubuntu 20.04.3 LTS

## Nextflow Installation

- Version: 21.10.0

## Container engine

- Engine: Docker
- version: 20.10.12
- Image tag: nfcore/eager:latest 7e4ca9d3f5c8

## Additional context

Is this related to the permission of docker?

**Comment by jfy133** [comment]
Hi @silvewheat - this is an issue with your docker configuration, as you correctly mention in your `additional context` section, rather than eager itself.

In most cases docker requires root permissions, which I suspect this is the issue here.  You will therefore need to check this accordingly.

As a tip: generally nf-core recommends the use of singularity, as this does not require root permissions and can 'use' docker images.
