### ISSUE TITLE
PMDTools with masked reference is borked

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#844]
I noticed PMDtools would have a similar issue as in #838 , but when fixing it I was told by @TCLamnidis my 'fix' didn't make sense, but I also didn't actually know what it was doing :sweat_smile:. Furhter investigation by @TCLamnidis showed the masked reference didn't even work in this case due to a missing flag. He will investigate and fix (I can't describe fully as I still don't understand :sweat_smile: )

**Comment by TCLamnidis** [comment]
# Clearer explanation for posterity
## Aim
When using pmdtools (especially on capture data), it has been shown that using a masked reference where the SNPs in the capture set are replaced with `N` (or an base that is not one of the SNP alleles) can help reduce reference bias. Doing so stops considering transition SNPs as potential damage when they appear in the start/end of fragments.

## Current implementation
```
if(params.snpcapture_bed){
        snpcap = (params.pmdtools_reference_mask) ? "--refseq ${params.pmdtools_reference_mask}" : ''
        log.info"######No reference mask specified for PMDtools, therefore ignoring that for downstream analysis!"
    } else {
        snpcap = ''
    }
```
Which will provide the `--refseq` option to pmdtools. 

## Problem with current implementation
Upon looking further into pmdtools, the `--refseq` option is only used to infer `--basecomposition`, which we are not doing here. 

## Intended solution
Users can provide a masked reference that is used instead of `${fasta}` in the `samtools calmd` command. If not provided, then use the original `${fasta}`.
